# Generated by Django 5.2.8 on 2025-11-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ROUTER", "Router"),
                            ("SWITCH", "Switch"),
                            ("AP", "Access Point"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("mac_address", models.CharField(max_length=17, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UP", "Online"),
                            ("DOWN", "Offline"),
                            ("MAINT", "Maintenance"),
                        ],
                        default="DOWN",
                        max_length=10,
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
