# Generated by Django 5.2.8 on 2025-11-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="location",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
